- html lang="en":
    - head:
        - meta charset="utf-8":
        - meta name="viewport" content="width=device-width,initial-scale=1":
        - title: Route-Graphics Playground

        - link rel="stylesheet" href="./public/theme.css":
        - script src="./public/main.js" type="module" defer:
        - script src="https://cdn.jsdelivr.net/npm/construct-style-sheets-polyfill@3.1.0/dist/adoptedStyleSheets.min.js":
        - script src="https://cdn.jsdelivr.net/npm/@rettangoli/ui@0.1.8/dist/rettangoli-iife-ui.min.js":

        - link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css":
        - script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js":
        - script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-yaml.min.js":
    - body:
        - "${content}"